In [ ]:
# NUMPY
# LIST MATH METHODS https://numpy.org/doc/stable/reference/routines.math.html

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [20]:
#FLOAT 64 - float Вещественные числа, с плавающей точкой.
a = np.array([1,2,-3,4,5,6.5],dtype='float64')
a

array([ 1. ,  2. , -3. ,  4. ,  5. ,  6.5])

In [12]:
# np.sctypeDict - Такая конструкция выведет все типы данных которые поддерживает NUMPY оч много !

In [35]:
# Есть Глюки ! НАДО ЗНАТЬ !!!
# При хранение в массиве с определенным типом в 8бит (1 байт) длинные числа не влазиют. 
#Он (numpy) их режет и трансформирует. (старое поведение) Как ниже ! (По новому ругается в консоль)
ss = np.array([89,2000,65,30,25,670]).astype(dtype='int8')
ss

array([ 89, -48,  65,  30,  25, -98], dtype=int8)

In [107]:
# Creating 3D Array

def hello():
    hello = "hello world"
    return hello

# И МАССИВАХ МОЖНО ДЕРЖАТЬ КОЛБЕКИ ! ЭТО ТАК КРУТО !
arr1 = [['a1','a1',hello()],['a2','a2','a2'],['a3','a3','a3']]
arr2 = [[21,22,23],[1,2,3],[1,2,3]]
arr3 = [['y','c1','c1'],['c2','x','c2'],['c3','c3','c3']]
tree_dim = [arr1,arr2,arr3]
tree_dim[0][0][2]



'hello world'

In [ ]:
# METHODS COLLECTION

In [120]:
# NP.EMPTY - Создает массив из произвольных чисел - можно указать тип данных в массиве - int8
emp = np.empty([2,2],dtype='int8')
emp

array([[0, 0],
       [0, 0]], dtype=int8)

In [123]:
# NP EYE - по диагонале еденички
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [124]:
# IDENTITY
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [125]:
# ZEROS
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [126]:
# ONES
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [127]:
# FULL - You may offer the values of array
np.full([5,5],-33)

array([[-33, -33, -33, -33, -33],
       [-33, -33, -33, -33, -33],
       [-33, -33, -33, -33, -33],
       [-33, -33, -33, -33, -33],
       [-33, -33, -33, -33, -33]])

In [135]:
# MULTIPLICATION INSIDE
np.array([10]*10)

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [141]:
# WITH STRINGS BY USING - MAT
# np.mat(['1,2,3,4'])
np.mat('1 2; 3 4')

matrix([[1, 2],
        [3, 4]])

In [152]:
# D I A G - int/letter in tuple will be put in diagonal line
# DIAGFLAT
# np.diagflat([1,2,3,4,5,6])
# diagflat almost the same behaviour - need exploration - read it !
np.diag(['a',2,3,4,5])


array([['a', '', '', '', ''],
       ['', '2', '', '', ''],
       ['', '', '3', '', ''],
       ['', '', '', '4', ''],
       ['', '', '', '', '5']], dtype='<U21')

In [159]:
# TRI - makes treenagle.  Below 1's... Upper side - zero's.    I N T E R E S T I N G !

np.tri(6) 

array([[1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1.]])

In [6]:
# TRIU - Makes values up
np.triu([7,7,7,7,7])

array([[7, 7, 7, 7, 7],
       [0, 7, 7, 7, 7],
       [0, 0, 7, 7, 7],
       [0, 0, 0, 7, 7],
       [0, 0, 0, 0, 7]])

In [17]:
# TRIL - makes values below(down)
np.tril([[[5,5,5,5,5],[6,6,6,6,6],[7,7,7,7,7]],[[4,4,4,4,4],[9,9,9,9,9],[8,8,8,8,8]],[[5,5,5,5,5],[6,6,6,6,6],[7,7,7,7,7]],[[4,4,4,4,4],[9,9,9,9,9],[8,8,8,8,8]]])

array([[[5, 0, 0, 0, 0],
        [6, 6, 0, 0, 0],
        [7, 7, 7, 0, 0]],

       [[4, 0, 0, 0, 0],
        [9, 9, 0, 0, 0],
        [8, 8, 8, 0, 0]],

       [[5, 0, 0, 0, 0],
        [6, 6, 0, 0, 0],
        [7, 7, 7, 0, 0]],

       [[4, 0, 0, 0, 0],
        [9, 9, 0, 0, 0],
        [8, 8, 8, 0, 0]]])

In [30]:
# VANDER - https://en.wikipedia.org/wiki/Vandermonde_matrix
# NEED TO LEARN MORE !!!
np.vander([4*6,5*4]) 

array([[24,  1],
       [20,  1]])

In [65]:
# ARANGE   >>> от "значение" , до "значение" , шаг "значение" - на выходе список множеством по шагам.
np.arange(1,6,0.383) # LAST INT NOT INCLUDED BUT FLOAT IS IT!

array([1.   , 1.383, 1.766, 2.149, 2.532, 2.915, 3.298, 3.681, 4.064,
       4.447, 4.83 , 5.213, 5.596, 5.979])

In [78]:
# ARANGE WITH PI VALUE - np.pi is pi value which ebedded in numpy
np.arange(0,np.pi,0.01,dtype='float64')
# np.pi = 3.141592653589793


array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  , 1.01, 1.02, 1.03, 1.04, 1.05, 1.06, 1.07, 1.08, 1.09,
       1.1 , 1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.2 ,
       1.21, 1.22, 1.23, 1.24, 1.25, 1.26, 1.27, 1.28, 1.29, 1.3 , 1.31,
       1.32, 1.33, 1.34, 1.35, 1.36, 1.37, 1.38, 1.39, 1.4 , 1.41, 1.42,
       1.43, 1.44, 1.45, 1.46, 1.47, 1.48, 1.49, 1.

In [91]:
# L I N S P A C E - МОЩЬ !!! ДЕЛИТ ОТРЕЗОК НА ТОЧКИ
# ПРИНЦИП. args = (start | stop | how much points?)
np.linspace(1, 10, 4,dtype='float64')


array([ 1.,  4.,  7., 10.])

In [92]:
# G E O M S P A C E - Amost the same as linspace()
np.geomspace(1,5,4, dtype='float64')

array([1.        , 1.70997595, 2.92401774, 5.        ])

In [93]:
# F R O M F U N C T I O N
np.fromfunction(lambda x,y: x*3 + y, [2,2])

array([[0., 1.],
       [3., 4.]])

In [95]:
# C O P Y - IMPORTANT - Copy it is not the same object !
some_array = np.array([1,2,3])
np.copy(some_array)

array([1, 2, 3])

In [96]:
# F R O M I T E R From iterable - any iterable !
def for_inside(n):
    for i in range(n):
        yield i
        
np.fromiter(for_inside(10),dtype='int8')
 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8)

In [129]:
# F R O M S T R I N G  - int string but if you do dtype...
# np.sctypeDict - check types
np.fromstring('1, 2, 3',dtype='int8',sep=",")

array([1, 2, 3], dtype=int8)

In [61]:
# S H A P E - Reshape with shape >> First arg is height 5 >> 2 is width
# R E S H A P E too - look below
dd = np.array([[1,2,3,4,5],[1,2,3,4,5]])
dd.shape = 5,2
dd


array([[1, 2],
       [3, 4],
       [5, 1],
       [2, 3],
       [4, 5]])

In [41]:
# R E S H A P E 
ss = dd.reshape(10)
ss

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [30]:
# T R A N S P O S I N G - Транспонирование - были значения по горизонтали, стали по вертикали.
dd.T

array([[1, 3, 5, 2, 4],
       [2, 4, 1, 3, 5]])

In [59]:
# WITHARDS WITH - R E S H A P E  and  S H A P E
# Если матрица из n положит и из n отрицательных(например) то можно указать в параметре -1
nine = np.array([-1,1,2,3,4,5,6,7,8,9])
nine.shape = -1,5
nine

array([[-1,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [68]:
# R A V E L - Ravel methods unravels complicated arrays
fx = np.array([[1, 3, 5, 2, 4],[2, 4, 1, 3, 5],[1,2,3,4,5]])
# Outcome is...
# >>> array([[1, 3, 5, 2, 4],
#        [2, 4, 1, 3, 5],
#        [1, 2, 3, 4, 5]])
fx.ravel()

array([1, 3, 5, 2, 4, 2, 4, 1, 3, 5, 1, 2, 3, 4, 5])

In [73]:
# R E S I Z E - With magic - refcheck=false
# Resizing with no rules
fx = np.array([[1, 3, 5, 2, 4],[2, 4, 1, 3, 5],[1,2,3,4,5]])
fx.resize(5,5, refcheck=False)
fx

array([[1, 3, 5, 2, 4],
       [2, 4, 1, 3, 5],
       [1, 2, 3, 4, 5],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
# E X P A N D _ D I M S
# - https://youtu.be/POgD3xN5Q6Y?list=PLA0M1Bcd0w8zmegfAUfFMiACPKfdW4ifD

In [43]:
import math
grid = np.full((10,10),[range(0,10)],dtype='int8')
print(grid)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


[4, 2, 0]
